version: '3'

services:
  api-solid-pg:
  image: bitnami/postgresql:latest
  ports:
    - 5432:5432
  enviroment:
    - POSTGRESQL_USERNAME=docker
    - POSTGRES_PASSWORD=docker
    - POSTGRESQL_DATABASE=apisolid
